/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ILayerZeroEndpoint } from "./ILayerZeroEndpoint";
export type { LayerZeroBridge } from "./LayerZeroBridge";
